// =============================================================================
// WHAT'S NEW & UPDATED
// Auto-generated by the Empire-HQ n8n publisher. Entries are prepended here
// whenever a lesson is published (NEW) or an existing lesson is refreshed
// (UPDATED). The home page renders the latest entries from this array.
// =============================================================================

export interface SiteUpdate {
  id: string
  title: string
  description: string
  date: string
  kind: "new" | "updated"
  href: string
}

export const ALL_UPDATES: SiteUpdate[] = [
  {
    "id": "resources-updated-2026-08-18",
    "title": "OSINT Resources",
    "description": "Refreshed: OSINT Resources",
    "date": "2026-08-18",
    "kind": "updated",
    "href": "/learn/resources"
  },
  {
    id: "case-file-planner",
    title: "Case File Planner",
    description:
      "Paste a collection target and get a cited OSINT 101 investigation plan. Foundations free; advanced techniques gated.",
    date: "2026-08-13",
    kind: "new",
    href: "/case-file",
  },
]

export const latestUpdates = ALL_UPDATES.slice(0, 5)
