// =============================================================================
// WHAT'S NEW & UPDATED
// Auto-generated by the Empire-HQ n8n publisher. Entries are prepended here
// whenever a lesson is published (NEW) or an existing lesson is refreshed
// (UPDATED). The home page renders the latest entries from this array.
// =============================================================================

export interface SiteUpdate {
  id: string
  title: string
  description: string
  date: string
  kind: "new" | "updated"
  href: string
}

export const ALL_UPDATES: SiteUpdate[] = [
  {
    "id": "resources-updated-2026-08-22",
    "title": "OSINT Resources Hub",
    "description": "Refreshed: OSINT Resources Hub",
    "date": "2026-08-22",
    "kind": "updated",
    "href": "/learn/resources"
  },
  {
    "id": "build-vs-buy-ai-updated-2026-08-22",
    "title": "The Million-Dollar Question: Build vs. Buy for AI Solutions",
    "description": "Refreshed: The Million-Dollar Question: Build vs. Buy for AI Solutions",
    "date": "2026-08-22",
    "kind": "updated",
    "href": "/learn/build-vs-buy-ai"
  },
  {
    "id": "llms-txt-updated-2026-08-20",
    "title": "Understanding Large Language Models (LLMs) in OSINT",
    "description": "Refreshed: Understanding Large Language Models (LLMs) in OSINT",
    "date": "2026-08-20",
    "kind": "updated",
    "href": "/learn/llms-txt"
  },
  {
    "id": "llm-updated-2026-08-20",
    "title": "Understanding Large Language Models (LLMs) for OSINT",
    "description": "Refreshed: Understanding Large Language Models (LLMs) for OSINT",
    "date": "2026-08-20",
    "kind": "updated",
    "href": "/learn/llm"
  },
  {
    "id": "pricing-updated-2026-08-20",
    "title": "Accurate Pricing for OSINT Training",
    "description": "Refreshed: Accurate Pricing for OSINT Training",
    "date": "2026-08-20",
    "kind": "updated",
    "href": "/learn/pricing"
  },
  {
    "id": "case-file-updated-2026-08-20",
    "title": "OSINT Case File Analysis: Identifying and Verifying Information",
    "description": "Refreshed: OSINT Case File Analysis: Identifying and Verifying Information",
    "date": "2026-08-20",
    "kind": "updated",
    "href": "/learn/case-file"
  },
  {
    "id": "requests-updated-2026-08-20",
    "title": "Mastering Information Requests for Open-Source Intelligence",
    "description": "Refreshed: Mastering Information Requests for Open-Source Intelligence",
    "date": "2026-08-20",
    "kind": "updated",
    "href": "/learn/requests"
  },
  {
    "id": "contact-updated-2026-08-20",
    "title": "Understanding Contact Information in OSINT",
    "description": "Refreshed: Understanding Contact Information in OSINT",
    "date": "2026-08-20",
    "kind": "updated",
    "href": "/learn/contact"
  },
  {
    "id": "contribute-updated-2026-08-20",
    "title": "Contributing to Open Source Intelligence (OSINT) Projects",
    "description": "Refreshed: Contributing to Open Source Intelligence (OSINT) Projects",
    "date": "2026-08-20",
    "kind": "updated",
    "href": "/learn/contribute"
  },
  {
    "id": "community-updated-2026-08-20",
    "title": "Community Building and Engagement",
    "description": "Refreshed: Community Building and Engagement",
    "date": "2026-08-20",
    "kind": "updated",
    "href": "/learn/community"
  },
  {
    "id": "resources-updated-2026-08-18",
    "title": "OSINT Resources",
    "description": "Refreshed: OSINT Resources",
    "date": "2026-08-18",
    "kind": "updated",
    "href": "/learn/resources"
  },
  {
    id: "case-file-planner",
    title: "Case File Planner",
    description:
      "Paste a collection target and get a cited OSINT 101 investigation plan. Foundations free; advanced techniques are Case File Pro — $19/mo.",
    date: "2026-08-13",
    kind: "new",
    href: "/case-file",
  },
]

export const latestUpdates = ALL_UPDATES.slice(0, 5)
